services:
  db:
    container_name: postgres_container
    image: postgres:14.18
    ports:
      - "5000:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  af:
    container_name: airflow_container
    image: apache/airflow:2.9.0
    ports:
      - 8000:8000
    environment:
      AIRFLOW_DATABASE_SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@db:5432/airflow_db
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    depends_on:
      - db
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
